default:
  image: golang:1.18

variables:
  PACKAGE_REGISTRY: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$CI_PROJECT_NAME

stages:
  - go-fmt
  - build
  - upload
  - release

go-fmt:
  stage: go-fmt
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

build:
  stage: build
  rules:
    # Build on every merge to master. Don't build on tag push
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - export VERSION=$(git describe --tags --always)
    - echo "VERSION=${VERSION}" >> build.env
  script:
    - go mod download
    - go build -race -ldflags "-X gitlab.com/${CI_PROJECT_PATH}/cmd.Version=${VERSION}" -o $CI_PROJECT_NAME
  artifacts:
    paths:
      - $CI_PROJECT_NAME
    reports:
      dotenv: build.env

upload:
  stage: upload
  image: curlimages/curl:latest
  dependencies: [build]
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file $CI_PROJECT_NAME $PACKAGE_REGISTRY/$VERSION/$CI_PROJECT_NAME

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Releasing version ${VERSION}"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
    ref: $CI_COMMIT_SHA
    assets:
      links:
        - name: $CI_PROJECT_NAME
          url: $PACKAGE_REGISTRY/$CI_COMMIT_TAG/$CI_PROJECT_NAME
