default:
  image: golang:1.18

variables:
  PACKAGE_REGISTRY: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$CI_PROJECT_NAME

stages:
  - lint
  - version
  - build
  - upload
  - release

go-fmt:
  stage: lint
  script:
    - test -z $(go fmt $(go list ./... | grep -v /vendor/))
    - go vet $(go list ./... | grep -v /vendor/)

hadolint:
  stage: lint
  image: hadolint/hadolint:2.9.2
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - Dockerfile
  script:
    - hadolint Dockerfile

version:
  stage: version
  script:
    - export VERSION=$(git describe --tags --always)
    - echo "Bumping version to ${VERSION}"
    - echo "VERSION=${VERSION}" >> version.env
  artifacts:
    reports:
      dotenv: version.env

docker:
  stage: build
  image: docker:20.10.17
  dependencies: [version]
  services: [docker:dind]
  rules:
    # Build on every merge to main. Don't build on tag push
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$VERSION
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE

binary:
  stage: build
  dependencies: [version]
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - go mod download
    - go build -race -ldflags "-X gitlab.com/${CI_PROJECT_PATH}/cmd.Version=${VERSION}" -o $CI_PROJECT_NAME
  artifacts:
    paths:
      - $CI_PROJECT_NAME

upload:
  stage: upload
  image: curlimages/curl:7.84.0
  dependencies: [version, binary]
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file $CI_PROJECT_NAME $PACKAGE_REGISTRY/$VERSION/$CI_PROJECT_NAME

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:v0.13.0
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Releasing version ${VERSION}"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
    ref: $CI_COMMIT_SHA
    assets:
      links:
        - name: $CI_PROJECT_NAME
          url: $PACKAGE_REGISTRY/$CI_COMMIT_TAG/$CI_PROJECT_NAME
