default:
  image: golang:1.18

variables:
  BINARY: dndcc.go

stages:
  - go-fmt
  - build
  - release

go-fmt:
  stage: go-fmt
  script:
    - test -z "$(go fmt $(go list ./... | grep -v /vendor/))"
    - go vet

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - go mod download
    - go build -race -o $BINARY
  artifacts:
    paths:
      - $BINARY

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules: [if: $CI_COMMIT_TAG] # Run if tag created manually
  script: [echo "Creating release"]
  release:
    tag_name: $CI_PIPELINE_ID
    description: $CI_PIPELINE_ID
    ref: $CI_COMMIT_SHA
